version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Helsinki
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    groups:
      production-patch-minor:
        dependency-type: production
        update-types: ["patch", "minor"]
      development-patch-minor:
        dependency-type: development
        update-types: ["patch", "minor"]
    commit-message:
      prefix: "chore"
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
